// src/components/About.vue
<script setup></script>

<template>
  <h1 class="aboutTitle">
    Behind the Keyboard
  </h1>
  <div class="aboutContent">
    <h3>Why coding?</h3>
    <p>
      I've been surrounded by technology since I was little and always loved solving problems. Whenever technology came into play, my family would come to me to fix it. I was their personal IT getting viruses off of their computers since middle school.

      Interestingly enough I didn't automatically go into computer science. I did some small coding projects on my own but I never formally learned programming until I went through a LaunchCode course in 2024. Now I'm back in school getting my degree in Computer Science at SIUE.
    </p>
    <h3>What are you currently learning and exploring?</h3>
    <p>
      Formally in school, I'm learning about how computers read code and C++ concepts but personally I've been playing around with AI and chat bots. I've been working on a Gemini based chatbot, toying with the idea of gamifying it and adding a relationship value to the 'character' that increases or decreases depending on how the 'character' likes the response.
    </p>
    <h3>What's your process for problem-solving?</h3>
    <p>
      I write things down and try to understand what exactly it is I'm trying to do. Most of the time it's scribbles that only I understand. I find that when I don't write things down, it's easy to get bogged down by the details and forget the main focus.
      <br>
      <br>
      So I write it down.
      Then I come up with possible solutions and do them.
      Sometimes they work and sometimes they don't.
    </p>
  </div>
</template>

// Portfolio-client/src/components/About.jsx
import '../App.css'
const About = () => {
    
    return (
      <>
      <div className='aboutContent'>
        <h1>Behind the Keyboard</h1>
        <p>Hi, I’m Sonnie Nguyen, a Computer Science student at Southern Illinois University Edwardsville.</p> 
        <p>
        <h5>Why coding?</h5>
        I’ve been surrounded by technology since I was little and always loved solving problems. Whenever technology came into play, my family would come to me to fix it. I was their personal IT getting viruses off of their computers since middle school. 

        Interestingly enough I didn’t automatically go into computer science. I did some small coding projects on my own but I never formally learned programming until I went through a LaunchCode course in 2024. Now I’m back in school getting my degree in Computer Science at SIUE.

        <h5>What are you currently learning and exploring? </h5>
        Formally in school, I’m learning about how computers read code and C++ concepts but personally I’ve been playing around with AI and chat bots. I’ve been working on a Gemini based chatbot, toying with the idea of gamifying it and adding a relationship value to the ‘character’ that increases or decreases depending on how the ‘character likes the response. 

        <h5>What’s your process for problem-solving?</h5>
        You probably aren’t actually curious but I’ll answer anyway.

        I am a stringent writer. Meaning that I write it down and try to understand what exactly it is I’m trying to do. I find that when I don’t write things down, it’s easy to get bogged down by the details and forget the main focus. 
        So I write it down. 
        Then I come up with possible solutions and do them.
        Sometimes they work and sometimes they don’t.</p>
      </div>
      </>
    );
}

export default About;
