// src/components/Card.vue
<script setup>
const props = defineProps({
  project: {
    type: Object,
    required: true,
  },
})

const placeholderClick = () => {
  window.open(props.project.link)
}
</script>

<template>
  <div
    class="project-card"
    @click="placeholderClick"
  >
    <div class="card">
      <div class="card-title nav-link">
        {{ project.Name }}
      </div>
      <div class="card-body">
        <p class="card-text">
          {{ project.Description }}
        </p>
      </div>
      <div class="cardButtons">
        <a
          class="projects-link"
          :href="project.link"
          target="_blank"
          rel="noopener noreferrer"
          @click.stop
        >
          Github Link
        </a>
      </div>
    </div>
  </div>
</template>

// Portfolio-client/src/components/Card.jsx
import { Link } from 'react-router-dom';
import {
    Card,
    CardBody,
    CardTitle,
    CardText,
    CardLink
} from 'reactstrap'

const Blog = ({project}) => {
const { title, description, link, id } = project;
console.log(id);
    return (
        <Card className='card'>
            <CardTitle>
                {title}
            </CardTitle>
            <CardBody>
                <CardText>
                    {description}
                </CardText>
            </CardBody>
            <Link href={link} target="_blank" rel="noopener noreferrer">
                Github Repo Link
            </Link>
            <Link to={`/post/${id}`} className="btn btn-primary">
            View More
            </Link>
        </Card>
    );
};

export default Blog;
