// src/components/Card.jsx
import { Link, useNavigate } from 'react-router-dom';
import {
    Card,
    CardBody,
    CardTitle,
    CardText,
    CardLink
} from 'reactstrap'

const Blog = ({project}) => {
    const { title, description, link, id } = project;
    const navigate = useNavigate();
    // const handleClick = () => {
    //     navigate(`/post/${id}`);
    // };

    const placeholderClick = () => {
        window.open(link);
    };

    return (
        <div className='project-card' onClick={placeholderClick}>
            <Card className='card'>
                <CardTitle className='nav-link'>
                    {title}
                </CardTitle>
                <CardBody>
                    <CardText>
                        {description}
                    </CardText>
                </CardBody>
                <div className='cardButtons'>
                <a className='projects-link'href={link} target="_blank" onClick={(e) => e.stopPropagation()} >
                    Github Link
                </a>
                {/* <Link to={`/post/${id}`} className="projects-link" onClick={(e) => e.stopPropagation()} >
                View More
                </Link> */}
                </div>
            </Card>
        </div>
    );
};

export default Blog;

// src/components/Card.vue
<script setup>
const props = defineProps({
  project: {
    type: Object,
    required: true,
  },
})

const placeholderClick = () => {
  window.open(props.project.link)
}
</script>

<template>
  <div
    class="project-card"
    @click="placeholderClick"
  >
    <div class="card">
      <div class="card-title nav-link">
        {{ project.Name }}
      </div>
      <div class="card-body">
        <p class="card-text">
          {{ project.Description }}
        </p>
      </div>
      <div class="cardButtons">
        <a
          class="projects-link"
          :href="project.link"
          target="_blank"
          rel="noopener noreferrer"
          @click.stop
        >
          Github Link
        </a>
      </div>
    </div>
  </div>
</template>
