// src/App.jsx
import './App.css'
import { Outlet,useLocation } from 'react-router-dom'
import Navigation from './Navigation.jsx'
import Footer from './Footer.jsx';

function App() {
  const location = useLocation();
  const isHomePage = location.pathname === '/';

  return (
    <div className={`app-container ${isHomePage ? 'home-page' : ''}`}>
      <Navigation/>
      <div className={`content-container ${isHomePage ? 'home-page' : ''}`}>
        <Outlet/>
      </div>
      <Footer/>
  
    </div>
  )
}

export default App

// src/App.vue
<script setup>
import { computed } from 'vue'
import { useRoute } from 'vue-router'
import Navigation from './Navigation.vue'
import Footer from './Footer.vue'

const route = useRoute()
const isHomePage = computed(() => route.path === '/')
</script>

<template>
  <div :class="['app-container', { 'home-page': isHomePage }]">
    <Navigation />
    <div :class="['content-container', { 'home-page': isHomePage }]">
      <router-view />
    </div>
    <Footer />
  </div>
</template>
