// Portfolio-client/src/Navigation.jsx
import {
    Collapse,
    Navbar,
    NavbarBrand,
    Nav,
    NavItem,
    NavbarToggler,
  } from 'reactstrap';
  import { useState, useEffect } from 'react'
  import { Link, useLocation } from 'react-router-dom'
  import './App.css'



  const Navigation = () => {
      const location = useLocation();
      const [isOpen, setIsOpen ] = useState(false);
      
      const toggle = () => setIsOpen(!isOpen);
      
    useEffect(() => {
        const handleClickOutside = (event) => {
            if(!event.target.closest('.navbar')) {
                setIsOpen(false);
            }
        };

        if(isOpen) {
            document.addEventListener('click', handleClickOutside);
        } else {
            document.removeEventListener('click', handleClickOutside);
        }

        return () => document.removeEventListener('click', handleClickOutside);
    }, [isOpen])

    useEffect(() => {
        setIsOpen(false);
    }, [location.pathname]);
    

    return (
       <>
       <Navbar light expand='md' className='fixed-top nav-bar ps-4' id='navbar-margin'>
            <NavbarBrand href='/'>
                <h1 className='title'>Sonnie Nguyen</h1>
            </NavbarBrand>
            <NavbarToggler onClick={toggle}/>
            <Collapse isOpen={isOpen}  className='navbar-collapse' navbar>
            <Nav className='ms-auto pe-4' navbar>
                <NavItem>
                    <Link to='/About' className='nav-link'
                    aria-current={location.pathname ==='/About' ? 'page': undefined}
                    >About</Link>
                </NavItem>
                <NavItem>
                    <Link to='/Projects' className='nav-link'
                    aria-current={location.pathname === '/Projects' ? 'page' : undefined}
                    >Projects</Link>
                </NavItem>
                <NavItem>
                    <Link to='/Resume' className='nav-link'
                    aria-current={location.pathname === '/Resume' ? 'page' : undefined}
                    >Resume</Link>
                </NavItem>
            </Nav>
            </Collapse>
       </Navbar>
       <div className="rounded-line"></div>
       </>
    );
  }

export default Navigation;

// src/Navigation.vue
<script setup>
import { ref, watch, onUnmounted } from 'vue'
import { useRoute } from 'vue-router'

const route = useRoute()
const isOpen = ref(false)

const toggle = () => {
  isOpen.value = !isOpen.value
}

const handleClickOutside = (event) => {
  if (!event.target.closest('.navbar')) {
    isOpen.value = false
  }
}

watch(isOpen, (open) => {
  if (open) {
    document.addEventListener('click', handleClickOutside)
  } else {
    document.removeEventListener('click', handleClickOutside)
  }
})

watch(
  () => route.path,
  () => {
    isOpen.value = false
  }
)

onUnmounted(() => {
  document.removeEventListener('click', handleClickOutside)
})
</script>

<template>
  <nav
    id="navbar-margin"
    class="navbar navbar-expand-md fixed-top nav-bar ps-4"
  >
    <router-link
      class="navbar-brand"
      to="/"
    >
      <h1 class="title">
        Sonnie Nguyen
      </h1>
    </router-link>
    <button
      class="navbar-toggler"
      type="button"
      aria-label="Toggle navigation"
      @click="toggle"
    >
      <span class="navbar-toggler-icon" />
    </button>
    <div
      class="collapse navbar-collapse"
      :class="{ show: isOpen }"
    >
      <ul class="navbar-nav ms-auto pe-4">
        <li class="nav-item">
          <router-link
            to="/About"
            class="nav-link"
          >
            About
          </router-link>
        </li>
        <li class="nav-item">
          <router-link
            to="/Projects"
            class="nav-link"
          >
            Projects
          </router-link>
        </li>
        <li class="nav-item">
          <router-link
            to="/Resume"
            class="nav-link"
          >
            Resume
          </router-link>
        </li>
      </ul>
    </div>
  </nav>
  <div class="rounded-line" />
</template>
